version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wordday_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: wordday
      POSTGRES_PASSWORD: wordday123
      POSTGRES_DB: wordday
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
